###login
POST localhost:8082/api/v1/auth/login
Content-Type: application/json

{
  "phone": "+998901234567",
  "password": "12345"
}

###registration
POST localhost:8082/api/v1/auth/registration
Content-Type: application/json

{
  "name":"Diyorbek",
  "surname": "Hamidov",
  "email": "diyorbekhamidov0519@gmail.com",
  "password": "12345"
}


###registrationByPhone
POST localhost:8082/api/v1/auth/registrationByphone
Content-Type: application/json

{
  "name":"Diyorbek",
  "surname": "Hamidov",
  "phone": "+998881231111",
  "password": "12345"
}

###verification
GET localhost:8082/api/v1/auth/verification/phone
Content-Type: application/json

{
"message": "7351",
  "phone": "+998881231111"
}