### create
POST localhost:8082/api/v1/tag/create
Content-Type: application/json
Authorization: Basic Kzk5ODkwMTIzNDU2NzoxMjM0NQ==

{
  "nameUz": "MOSKVA",
  "nameRu": "МОСКВА",
  "nameEn": "MOSCOW"
}
